name: prova_flutter
description: "Projeto criado para processo de seleção da Target Sistemas."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  url_launcher: ^6.1.6
  http: ^1.1.2
  mobx: ^2.2.3+1
  shared_preferences: ^2.2.2
  flutter_mobx: ^2.2.0+1
  build_runner: ^2.4.7
  mobx_codegen: ^2.4.1
  confirm_dialog: ^1.0.3
  loading_animation_widget: ^1.2.0+4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
